version: '3'
services:
  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
#      - ./scripts/mongo/init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
#      - ./scripts/mongo/init:/home/mongodb
      - mongo-volume:/data/db
    ports:
      - ${MONGO_DB_PORT}:27017

  mongo-express:
    image: mongo-express:1.0.0-20
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/

volumes:
  mongo-volume: